### ISSUE TITLE
Run PHPUnit with composer

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/t3_tactician#4]
Hi,

I would like to suggest adding the phpunit command to composer scripts. 
so they can be executed with 

`$ composer test:unit` makes it easier to run the tests, without having to know the complete command, disadvantage is that the `--colors` parameter will be ignore, as the output is from composer and not from terminal directly. 

Doing it like this for the crawler:
https://github.com/AOEpeople/crawler/blob/typo3v9/composer.json#L58

If you run without having a phpunit binary, it will trigger a composer update first.

**Comment by sabbelasichon** [comment]
I am fine with the current implementation and the benefit of using the --colors option.
